#+title: Notes
* [#A] Add a test suite
:PROPERTIES:
:CREATED_TIME: [2020-02-09 Sun 13:32]
:END:
Add behavior tests.
* [#A] The correct behavior of git-identity-mode
:PROPERTIES:
:CREATED_TIME: [2020-02-09 Sun 13:29]
:END:
=git-identity-mode= should behave as described in this section.

| Effective identity | Has an expected identity | No expected identity |
|--------------------+--------------------------+----------------------|
| Local              | (1)                       | Pass                 |
| Global             | (2)                       | Pass                 |
| None               | Confirm                  | Select               |

(1) If the repository has an effective identity set in the local git config and also has a derived/expected identity, =git-identity-mode= should behave as follows:

- If the effective identity matches the expected identity, it does nothing.
- If the two identities mismatch, it displays a warning.

(2) If the repository has an effective identity set in the global git config and has a derived/expected identity, =git-identity-mode= should behave as follows:

- If the effective identity matches the expected identity, it does nothing.
- If the two identities mismatch, it asks the user if he wants to set the expected identity in the local git config.

In other cases, it should behave as follows:

- /Confirm/ means that this package asks the user if he/she wants to set the expected identity in the local git config.
- /Pass/ means that =git-identity-mode= has no effect on the workflow.
- /Select/ means that =git-identity-mode= lets the user select an identity from the configured identity list.
* [#B] Tabular presentation
This feature is currently work in progress in =tabular= branch.
* [#B] A new scheme for identity configuration
:PROPERTIES:
:CREATED_TIME: [2020-02-09 Sun 13:33]
:END:
This feature is currently work in progress in =feature/clone= branch.
* [#B] Cloning remote repositories
